export const ErrorCode = {
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  TRANSFER_NOT_FOUND: "TRANSFER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  SELF_TRANSFER_NOT_ALLOWED: "SELF_TRANSFER_NOT_ALLOWED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
